name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for taking the time to suggest a new feature. Please fill in the following details to help us understand your request.
    - type: textarea
      id: feature-description
      attributes:
          label: Feature Description
          description: Describe the feature you'd like to see added
          placeholder: I would like to see X feature because it would help with Y...
      validations:
          required: true
    - type: textarea
      id: use-case
      attributes:
          label: Use Case
          description: Describe the specific use case or scenario where this feature would be valuable
          placeholder: This feature would be useful when...
      validations:
          required: true
    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed Solution
          description: If you have any specific ideas about how this feature could be implemented, please share them
          placeholder: This could be implemented by...
      validations:
          required: false
    - type: dropdown
      id: impact
      attributes:
        label: Impact Level
        description: How would you categorize the impact of this feature?
        options:
        - Minor Enhancement
        - Significant Improvement
        - Major Feature
        - Breaking Change
      validations:
        required: true
    - type: input
      id: package-version
      attributes:
          label: Package Version
          description: What version of our Package are you currently using?
          placeholder: 0.0.0
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or examples about the feature request here
      validations:
          required: false
